#This is an example R script file demonstrating how to run DEseq2 on counts data
#Load relevant packages
library(DESeq2)
library(gplots)
library(tidyverse)
library(dplyr)

#Import the counts data generated by HTSeq
counts.data <- read_tsv(file="example-htseq-counts.tsv")

#Import a metadata file describing the samples

#Construct a DESeq DataSet object from the counts data
counts.deseq.ds <- DESeqDataSetFromMatrix()

#Run the DESeq function to compute fold changes and p-values between control and treatment
deseq.object <- DESeq(counts.deseq.ds)
deseq.results <- results(deseq.object)

#Visualize the full DESeq output with a volcano plot to look at fold change distr and significant genes
with(deseq.results, plot(log2FoldChange, -log10(pvalue), pch=20, main="Volcano Plot", xlim=c(-3,3)))

#Color specific points on the volcano plot with sufficiently low p-values and sufficiently high fold changes
with(subset(deseq.results, padj < 0.01), points(log2FoldChange, -log10(pvalue),pch=20, col="lightblue"))
with(subset(deseq.results, padj < 0.01 & abs(log2FoldChange) >= 2), points(log2FoldChange, -log10(pvalue), pch=20, col="darkred"))
