{% set raw_version = environ.get('GIT_DESCRIBE_TAG', 'gunknown') %}
{% set version = raw_version[1:] if raw_version.startswith('v') else raw_version %}
{% set name = "carc_tutorial" %}

package:
  name: {{ name }}
  version: "{{ version }}"

source:
  path: ..

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python >=3.6
    - bash
    - setuptools

test:
  commands:
    - carc-jobs-example --help
    - carc-migrate --help

about:
  home: https://github.com/ryanreyn/CARC_Tutorial
  license: MIT
  summary: CLI tools and bash wrappers for cluster computing efforts
  dev_url: https://github.com/ryanreyn/CARC_Tutorial
